package LoadBalancerAutoScaler.LoadBalancerUtils;

import java.util.Set;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBDocument;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIgnore;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName="CNV-Project-logs")
public class MetricItem {

    private String id;
    private int branchesTaken;
    private int branchesNotTaken;
    private int fieldLoadCount;
    private int fieldStoreCount;
    private int loadCount;
    private int storeCount;
    private String solverStrategy;
    private int unassigned = -1;
    private int nCol = -1;
    private int nLin = -1;

    @DynamoDBHashKey(attributeName="id")
    public String getId() { return id; }
    public void setId(String value) { id = value; }

    @DynamoDBAttribute(attributeName="branchesTaken")
    public int getBranchesTaken() {return branchesTaken; }
    public void setBranchesTaken(int value) { branchesTaken = value; }

    @DynamoDBAttribute(attributeName="branchesNotTaken")
    public int getBranchesNotTaken() {return branchesNotTaken; }
    public void setBranchesNotTaken(int value) { branchesNotTaken = value; }

    @DynamoDBAttribute(attributeName="fieldLoadCount")
    public int getFieldLoadCount() {return fieldLoadCount; }
    public void setFieldLoadCount(int value) { fieldLoadCount = value; }

    @DynamoDBAttribute(attributeName="fieldStoreCount")
    public int getFieldStoreCount() {return fieldStoreCount; }
    public void setFieldStoreCount(int value) { fieldStoreCount = value; }

    @DynamoDBAttribute(attributeName="loadCount")
    public int getLoadCount() {return loadCount; }
    public void setLoadCount(int value) { loadCount = value; }

    @DynamoDBAttribute(attributeName="storeCount")
    public int getStoreCount() {return storeCount; }
    public void setStoreCount(int value) { storeCount = value; }

    @DynamoDBAttribute(attributeName="solverStrategy")
    public String getSolverStrategy() {return solverStrategy; }
    public void setSolverStrategy(String value) { solverStrategy = value; }

    @DynamoDBAttribute(attributeName="unassigned")
    public int getUnassigned() { return unassigned; }
    public void setUnassigned(int value) { unassigned = value; }

    @DynamoDBAttribute(attributeName="nCol")
    public int getNCol() { return nCol; }
    public void setNCol(int value) { nCol = value; }

    @DynamoDBAttribute(attributeName="nLin")
    public int getNLin() { return nLin; }
    public void setNLin(int value) { nLin = value; }
}